# Railway configuration file
[build]
builder = "dockerfile"

[deploy]
startCommand = "gunicorn --bind 0.0.0.0:5000 --workers 2 --timeout 30 app:app"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[env]
FLASK_ENV = "production"
