"""Initial migration from schema.sql

Revision ID: 182183820ac5
Revises: 
Create Date: 2025-10-19 16:32:42.508420

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '182183820ac5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('board_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mosque_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('position', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['mosque_id'], ['mosques.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mosque_features',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mosque_id', sa.Integer(), nullable=False),
    sa.Column('feature_name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['mosque_id'], ['mosques.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mosque_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mosque_id', sa.Integer(), nullable=False),
    sa.Column('year', sa.String(length=10), nullable=False),
    sa.Column('event_title', sa.String(length=255), nullable=False),
    sa.Column('event_description', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['mosque_id'], ['mosques.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prayer_times',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mosque_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('fajr', sa.Time(), nullable=False),
    sa.Column('dhuhr', sa.Time(), nullable=False),
    sa.Column('asr', sa.Time(), nullable=False),
    sa.Column('maghrib', sa.Time(), nullable=False),
    sa.Column('isha', sa.Time(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['mosque_id'], ['mosques.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mosque_id', 'date')
    )
    op.create_index('idx_prayer_times_mosque_date', 'prayer_times', ['mosque_id', 'date'], unique=False)
    op.create_table('blog_posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('excerpt', sa.Text(), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('featured_image', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_blog_posts_published', 'blog_posts', ['status', 'published_at'], unique=False)
    op.create_table('contact_submissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('mosque_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('responded_by', sa.Integer(), nullable=True),
    sa.Column('response', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['mosque_id'], ['mosques.id'], ),
    sa.ForeignKeyConstraint(['responded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_contact_submissions_status', 'contact_submissions', ['status'], unique=False)
    op.create_table('fundraising_campaigns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mosque_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('target_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('current_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['mosque_id'], ['mosques.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('janazah_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mosque_id', sa.Integer(), nullable=False),
    sa.Column('deceased_name', sa.String(length=255), nullable=False),
    sa.Column('deceased_age', sa.Integer(), nullable=True),
    sa.Column('deceased_date', sa.Date(), nullable=False),
    sa.Column('prayer_date', sa.Date(), nullable=False),
    sa.Column('prayer_time', sa.Time(), nullable=False),
    sa.Column('burial_location', sa.String(length=255), nullable=True),
    sa.Column('contact_person', sa.String(length=255), nullable=True),
    sa.Column('contact_phone', sa.String(length=20), nullable=True),
    sa.Column('contact_email', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['mosque_id'], ['mosques.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_janazah_events_date', 'janazah_events', ['prayer_date'], unique=False)
    op.create_table('mosque_access_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('mosque_id', sa.Integer(), nullable=True),
    sa.Column('mosque_name', sa.String(length=255), nullable=True),
    sa.Column('motivation', sa.Text(), nullable=True),
    sa.Column('contact_email', sa.String(length=255), nullable=True),
    sa.Column('contact_phone', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('admin_notes', sa.Text(), nullable=True),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.Column('processed_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['mosque_id'], ['mosques.id'], ),
    sa.ForeignKeyConstraint(['processed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_mosque_access_requests_status', 'mosque_access_requests', ['status'], unique=False)
    op.create_table('password_reset_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_index('idx_password_reset_tokens_user', 'password_reset_tokens', ['user_id'], unique=False)
    op.drop_table('news')
    op.drop_table('notifications')
    op.drop_table('notification_templates')
    op.drop_table('user_activity')
    op.drop_table('notification_preferences')
    op.drop_table('page_views')
    op.drop_table('payment_methods')
    op.drop_table('campaigns')
    op.drop_table('analytics_events')
    op.add_column('donations', sa.Column('payment_status', sa.String(length=50), nullable=True))
    op.add_column('donations', sa.Column('transaction_id', sa.String(length=255), nullable=True))
    op.add_column('donations', sa.Column('is_anonymous', sa.Boolean(), nullable=True))
    op.alter_column('donations', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.alter_column('donations', 'donor_name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               nullable=True)
    op.alter_column('donations', 'donor_email',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('donations', 'amount',
               existing_type=sa.REAL(),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=False)
    op.alter_column('donations', 'payment_method',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.create_index('idx_donations_mosque', 'donations', ['mosque_id'], unique=False)
    op.create_foreign_key(None, 'donations', 'fundraising_campaigns', ['campaign_id'], ['id'])
    op.drop_column('donations', 'stripe_payment_intent_id')
    op.drop_column('donations', 'donor_phone')
    op.drop_column('donations', 'donation_type')
    op.drop_column('donations', 'currency')
    op.drop_column('donations', 'status')
    op.add_column('events', sa.Column('is_recurring', sa.Boolean(), nullable=True))
    op.add_column('events', sa.Column('recurring_pattern', sa.String(length=50), nullable=True))
    op.add_column('events', sa.Column('current_attendees', sa.Integer(), nullable=True))
    op.add_column('events', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.alter_column('events', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.alter_column('events', 'mosque_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('events', 'title',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('events', 'event_type',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=True,
               existing_server_default=sa.text("'event'"))
    op.create_index('idx_events_mosque_date', 'events', ['mosque_id', 'event_date'], unique=False)
    op.add_column('media_files', sa.Column('mosque_id_ref', sa.Integer(), nullable=True))
    op.alter_column('media_files', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.alter_column('media_files', 'filename',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('media_files', 'original_filename',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('media_files', 'file_path',
               existing_type=sa.TEXT(),
               type_=sa.String(length=500),
               existing_nullable=False)
    op.alter_column('media_files', 'file_size',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('media_files', 'file_type',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('media_files', 'mime_type',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               nullable=True)
    op.drop_constraint(None, 'media_files', type_='foreignkey')
    op.drop_constraint(None, 'media_files', type_='foreignkey')
    op.create_foreign_key(None, 'media_files', 'mosques', ['mosque_id_ref'], ['id'])
    op.add_column('mosques', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.alter_column('mosques', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.alter_column('mosques', 'name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('mosques', 'phone',
               existing_type=sa.TEXT(),
               type_=sa.String(length=20),
               existing_nullable=True)
    op.alter_column('mosques', 'email',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('mosques', 'website',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('mosques', 'imam_name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('mosques', 'latitude',
               existing_type=sa.REAL(),
               type_=sa.Numeric(precision=10, scale=8),
               existing_nullable=True)
    op.alter_column('mosques', 'longitude',
               existing_type=sa.REAL(),
               type_=sa.Numeric(precision=11, scale=8),
               existing_nullable=True)
    op.create_index('idx_mosques_active', 'mosques', ['is_active'], unique=False)
    op.add_column('user_sessions', sa.Column('session_token', sa.String(length=255), nullable=False))
    op.alter_column('user_sessions', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.create_unique_constraint(None, 'user_sessions', ['session_token'])
    op.drop_column('user_sessions', 'token')
    op.add_column('users', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.alter_column('users', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.alter_column('users', 'email',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('users', 'password_hash',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('users', 'first_name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.alter_column('users', 'last_name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.alter_column('users', 'phone',
               existing_type=sa.TEXT(),
               type_=sa.String(length=20),
               existing_nullable=True)
    op.alter_column('users', 'role',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=True,
               existing_server_default=sa.text("'user'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("'user'"))
    op.alter_column('users', 'phone',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('users', 'last_name',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('users', 'first_name',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('users', 'password_hash',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('users', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.drop_column('users', 'updated_at')
    op.add_column('user_sessions', sa.Column('token', sa.TEXT(), nullable=False))
    op.drop_constraint(None, 'user_sessions', type_='unique')
    op.alter_column('user_sessions', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.drop_column('user_sessions', 'session_token')
    op.drop_index('idx_mosques_active', table_name='mosques')
    op.alter_column('mosques', 'longitude',
               existing_type=sa.Numeric(precision=11, scale=8),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('mosques', 'latitude',
               existing_type=sa.Numeric(precision=10, scale=8),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('mosques', 'imam_name',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('mosques', 'website',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('mosques', 'email',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('mosques', 'phone',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('mosques', 'name',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('mosques', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.drop_column('mosques', 'updated_at')
    op.drop_constraint(None, 'media_files', type_='foreignkey')
    op.create_foreign_key(None, 'media_files', 'campaigns', ['campaign_id'], ['id'])
    op.create_foreign_key(None, 'media_files', 'events', ['event_id'], ['id'])
    op.alter_column('media_files', 'mime_type',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               nullable=False)
    op.alter_column('media_files', 'file_type',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('media_files', 'file_size',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('media_files', 'file_path',
               existing_type=sa.String(length=500),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('media_files', 'original_filename',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('media_files', 'filename',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('media_files', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.drop_column('media_files', 'mosque_id_ref')
    op.drop_index('idx_events_mosque_date', table_name='events')
    op.alter_column('events', 'event_type',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("'event'"))
    op.alter_column('events', 'title',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('events', 'mosque_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('events', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.drop_column('events', 'updated_at')
    op.drop_column('events', 'current_attendees')
    op.drop_column('events', 'recurring_pattern')
    op.drop_column('events', 'is_recurring')
    op.add_column('donations', sa.Column('status', sa.TEXT(), server_default=sa.text("'pending'"), nullable=True))
    op.add_column('donations', sa.Column('currency', sa.TEXT(), server_default=sa.text("'EUR'"), nullable=True))
    op.add_column('donations', sa.Column('donation_type', sa.TEXT(), server_default=sa.text("'general'"), nullable=True))
    op.add_column('donations', sa.Column('donor_phone', sa.TEXT(), nullable=True))
    op.add_column('donations', sa.Column('stripe_payment_intent_id', sa.TEXT(), nullable=True))
    op.drop_constraint(None, 'donations', type_='foreignkey')
    op.drop_index('idx_donations_mosque', table_name='donations')
    op.alter_column('donations', 'payment_method',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('donations', 'amount',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.REAL(),
               existing_nullable=False)
    op.alter_column('donations', 'donor_email',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('donations', 'donor_name',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               nullable=False)
    op.alter_column('donations', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.drop_column('donations', 'is_anonymous')
    op.drop_column('donations', 'transaction_id')
    op.drop_column('donations', 'payment_status')
    op.create_table('analytics_events',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('event_type', sa.TEXT(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('mosque_id', sa.INTEGER(), nullable=True),
    sa.Column('event_data', sa.TEXT(), nullable=True),
    sa.Column('ip_address', sa.TEXT(), nullable=True),
    sa.Column('user_agent', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['mosque_id'], ['mosques.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('campaigns',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('title', sa.TEXT(), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('target_amount', sa.REAL(), nullable=False),
    sa.Column('current_amount', sa.REAL(), server_default=sa.text('0'), nullable=True),
    sa.Column('mosque_id', sa.INTEGER(), nullable=True),
    sa.Column('created_by', sa.INTEGER(), nullable=True),
    sa.Column('status', sa.TEXT(), server_default=sa.text("'active'"), nullable=True),
    sa.Column('start_date', sa.DATE(), nullable=True),
    sa.Column('end_date', sa.DATE(), nullable=True),
    sa.Column('featured_image', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['mosque_id'], ['mosques.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payment_methods',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('stripe_payment_method_id', sa.TEXT(), nullable=True),
    sa.Column('card_brand', sa.TEXT(), nullable=True),
    sa.Column('card_last_four', sa.TEXT(), nullable=True),
    sa.Column('is_default', sa.BOOLEAN(), server_default=sa.text('0'), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stripe_payment_method_id')
    )
    op.create_table('page_views',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('page_path', sa.TEXT(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('session_id', sa.TEXT(), nullable=True),
    sa.Column('ip_address', sa.TEXT(), nullable=True),
    sa.Column('user_agent', sa.TEXT(), nullable=True),
    sa.Column('referrer', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notification_preferences',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('notification_type', sa.TEXT(), nullable=False),
    sa.Column('email_enabled', sa.BOOLEAN(), server_default=sa.text('1'), nullable=True),
    sa.Column('push_enabled', sa.BOOLEAN(), server_default=sa.text('1'), nullable=True),
    sa.Column('sms_enabled', sa.BOOLEAN(), server_default=sa.text('0'), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'notification_type')
    )
    op.create_table('user_activity',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('activity_type', sa.TEXT(), nullable=False),
    sa.Column('activity_data', sa.TEXT(), nullable=True),
    sa.Column('ip_address', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notification_templates',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('template_name', sa.TEXT(), nullable=False),
    sa.Column('notification_type', sa.TEXT(), nullable=False),
    sa.Column('title_template', sa.TEXT(), nullable=False),
    sa.Column('message_template', sa.TEXT(), nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('1'), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('template_name')
    )
    op.create_table('notifications',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('mosque_id', sa.INTEGER(), nullable=True),
    sa.Column('title', sa.TEXT(), nullable=False),
    sa.Column('message', sa.TEXT(), nullable=False),
    sa.Column('notification_type', sa.TEXT(), nullable=False),
    sa.Column('priority', sa.TEXT(), server_default=sa.text("'normal'"), nullable=True),
    sa.Column('is_read', sa.BOOLEAN(), server_default=sa.text('0'), nullable=True),
    sa.Column('action_url', sa.TEXT(), nullable=True),
    sa.Column('metadata', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('expires_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['mosque_id'], ['mosques.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('news',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('title', sa.TEXT(), nullable=False),
    sa.Column('content', sa.TEXT(), nullable=False),
    sa.Column('excerpt', sa.TEXT(), nullable=True),
    sa.Column('author_id', sa.INTEGER(), nullable=True),
    sa.Column('published_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('status', sa.TEXT(), server_default=sa.text("'published'"), nullable=True),
    sa.Column('featured_image', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index('idx_password_reset_tokens_user', table_name='password_reset_tokens')
    op.drop_table('password_reset_tokens')
    op.drop_index('idx_mosque_access_requests_status', table_name='mosque_access_requests')
    op.drop_table('mosque_access_requests')
    op.drop_index('idx_janazah_events_date', table_name='janazah_events')
    op.drop_table('janazah_events')
    op.drop_table('fundraising_campaigns')
    op.drop_index('idx_contact_submissions_status', table_name='contact_submissions')
    op.drop_table('contact_submissions')
    op.drop_index('idx_blog_posts_published', table_name='blog_posts')
    op.drop_table('blog_posts')
    op.drop_index('idx_prayer_times_mosque_date', table_name='prayer_times')
    op.drop_table('prayer_times')
    op.drop_table('mosque_history')
    op.drop_table('mosque_features')
    op.drop_table('board_members')
    # ### end Alembic commands ###
